FROM python:3.11-slim

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/utils/add_weight_config.py .
COPY src/utils/default_weight_config.json .

CMD python add_weight_config.py --json default_weight_config.json