FROM python:3.11-slim

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/processing/tweet_processor.py tweet_processor.py
COPY src/processing/mindshare_calculator.py mindshare_calculator.py

CMD ["bash", "-c", "while true; do python tweet_processor.py && python mindshare_calculator.py; sleep 50; done"]